version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: pdb
    ports:
      - '5432:5432'

  api:
    build: ./
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: 123456
      DB_NAME: pdb
    volumes:
      - /app/node_modules
      - ./:/app
    depends_on:
      - db
    ports:
      - '5000:5000'
