version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pdb
    ports:
      - '5432:5432'

  api:
    build: ./
    environment:
      NODE_ENV: development
    volumes:
      - /app/node_modules
      - ./:/app
    depends_on:
      - db
    ports:
      - '5000:5000'
