version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: taskmanagerdb
    ports:
      - '5432:5432'

  # api:
  #   build: ./
  #   environment:
  #     DATABASE_URI: postgres://postgres:123456@db:5432/taskmanagerdb
  #   volumes:
  #     - ./:/usr/src/task-manager
  #     - /usr/src/task-manager/node_modules
  #   depends_on:
  #     - db
  #   ports:
  #     - '5000:5000'
